export const paths = {
  HOME: "/",
  DENTAL: "dental",
  ABOUT: "about",
  MY_QR: "qr",
  MAP: "map",
  NEWS: "news",
  VIDEO: "video",
  RETREATMENT: "retreatment",
  RESERVATION: "reservation",
  INSURANCE: "insurance",
  PARKING: "parking",
  PRODUCT: "product",
  INFO: "info",
  CONFIRM: "confirm",
  REGISTER: "register",
  SCHEDULE: "schedule",
  EDIT: "edit",
  COMPLETE: "complete",
  HISTORY: "history",
  SIGNATURE: "signature",
  CARE: "care",
  HEALTH: "health",
};
