export const paths = {
    HOME: "/",
    TOURNAMENT: "tournament",
    PROGRAM: "program",
    CALENDAR: "calendar",
    SHOP: "shop",
    NEWS: "news",
    RESULT: "result",
    GALLERY: "gallery",
    MYINFO: "my-info",
    LOGIN: "login",
    LOGOUT: "logout",
    POLICY: "policy",
    PRIVACY: "privacy",
    TERMS: "terms",
    DETAIL: "detail",
    JOIN: "join",
    FIND_EMAIL: "find-email",
    FIND_PASSWORD: "find-password",
    COURSE: "course",
};
