import type { Metadata, Viewport } from "next";
import { ApolloWrapper } from "@apollo-client/ApolloProvider";
import StyledComponentsProvider from "@styles/StyledComponentsProvider";
import Header from "@components/layout/header/Header";
import Footer from "@components/layout/footer/Footer";

export const metadata: Metadata = {
  title: {
    template: "%s",
    default: "Rock N Run",
  },
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  // 뷰포트 확대 금지
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  minimumScale: 1,
  userScalable: true,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ApolloWrapper>
          <StyledComponentsProvider>
            <Header />
            {children}
            <Footer />
          </StyledComponentsProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
