import type { Metadata, Viewport } from "next";
import Script from "next/script";
import { ApolloWrapper } from "@apollo-client/ApolloProvider";
import StyledComponentsProvider from "@styles/StyledComponentsProvider";
import Header from "@components/layout/header/Header";
import Footer from "@components/layout/footer/Footer";

export const metadata: Metadata = {
  title: {
    template: "%s",
    default: "Rock N Run",
  },
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  // 뷰포트 확대 금지
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  minimumScale: 1,
  userScalable: true,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ApolloWrapper>
          <StyledComponentsProvider>
            <div id="google_translate_element"></div>
            <Script
              src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
              strategy="afterInteractive"
            />
            <Script id="google-translate-init" strategy="afterInteractive">
              {`
                function googleTranslateElementInit() {
                  new google.translate.TranslateElement(
                    {
                      pageLanguage: 'auto',
                      includedLanguages: 'en,ko',
                      layout: google.translate.TranslateElement.InlineLayout.VERTICAL,
                    },
                    'google_translate_element'
                  );
                }
              `}
            </Script>
            <Header />
            {children}

            <Footer />
          </StyledComponentsProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
